### ISSUE TITLE
제네닉 타입 선언 

### ISSUE THREAD

**Issue by mocha-Bread** [LEEMOARE/GOAT_41#21]
https://github.com/LEEMOARE/GOAT_41/blob/b773c54e90b46309c3671db166d8d5687c73bde9/src/train_all.py#L17

여기서 소괄호로 코드를 돌렸을떄는 오류가 떴는데 대괄호로 바꾸니까 해결이 됐습니다  어떤게 문제였는지 궁금합니다

**Comment by dongseop-kim** [comment]
앗.. type hint일땐 대괄호로 하는게 문법상 맞습니다! 제가 틀렸네요

**Comment by mocha-Bread** [comment]
넵 알겠습니당
